//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImagesDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageInfo
    {
        public long ImageInfoId { get; set; }
        public int JobId { get; set; }
        public string LocalUrl { get; set; }
        public string RemoteUrl { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Size { get; set; }
        public string ContentType { get; set; }
    }
}
